import type { Task } from './types'

export const mockTasks: Task[] = [
  {
    id: 't-1',
    clientId: '1',
    projectId: '1',
    title: 'Pozvati klijenta za potvrdu termina',
    description: 'Kratak follow-up poziv',
    type: 'poziv',
    status: 'u_radu',
    assignedToUserId: 'user-1',
    assignedToLabel: 'Marko',
    dueDate: '2026-05-02',
    timeSpentMinutes: 20,
    materialCost: 0,
    laborCost: 500,
  },
  {
    id: 't-2',
    clientId: '1',
    projectId: '1',
    title: 'Poslati predlog rasporeda reklama',
    description: 'Email sa finalnim rasporedom',
    type: 'mail',
    status: 'dodeljen',
    assignedToUserId: 'user-2',
    assignedToLabel: 'Jelena',
    dueDate: '2026-05-05',
  },
  {
    id: 't-3',
    clientId: '1',
    projectId: '2',
    title: 'Obilazak lokacije pre postavke',
    description: 'Provera dimenzija i pozicija',
    type: 'sastanak',
    status: 'zavrsen',
    assignedToUserId: 'user-1',
    assignedToLabel: 'Marko',
    dueDate: '2026-04-25',
    timeSpentMinutes: 60,
    materialCost: 0,
    laborCost: 1500,
  },
  {
    id: 't-4',
    clientId: '1',
    projectId: '2',
    title: 'Nabavka materijala za pult',
    description: 'Dogovor i priprema materijala',
    type: 'interni_zadatak',
    status: 'na_cekanju',
    assignedToUserId: 'finance-1',
    assignedToLabel: 'Finansije',
    dueDate: '2026-05-08',
    timeSpentMinutes: 15,
    materialCost: 12000,
    laborCost: 375,
  },
  {
    id: 't-5',
    clientId: '1',
    projectId: '3',
    title: 'Finalna interna evaluacija pilota',
    description: 'Zatvaranje internog pilot ciklusa',
    type: 'interni_zadatak',
    status: 'naplacen',
    assignedToUserId: 'user-2',
    assignedToLabel: 'Jelena',
    dueDate: '2026-04-10',
    billingStatus: 'paid',
    timeSpentMinutes: 45,
    materialCost: 0,
    laborCost: 1125,
  },
]
